HEISPath: C:/HEIS/
HEISCompressedPath: C:/HEIS/DataCompressed/
HEISAccessPath: C:/HEIS/DataAccess/
HEISRawPath: C:/HEIS/DataRaw/
HEISProcessedPath: C:/HEIS/DataProcessed/
HEISResultsPath: C:/HEIS/DataResults/
HEISWeightsPath: ../Data/SamplingWeights/
HEISWeightFileName: HHWeights
HEISCountyCodePath: ../Data/CountyCodes8791/
HEISCountyCodeFileName: ShCode
startyear: 83.0
endyear: 100.0
baseBundleyear: 95.0
startmonth: 0.0
endmonth: 0.0
predictionyear: 99.0
predictionmonth: 0.0
RawDataWebAddress: https://www.amar.org.ir/Portals/0/amarmozuii/re_DataRaw_63_95_Info/
MetaDataFilePath: ../Data/MetaData.xlsx
GeoInfoFilePath: ../Data/Archive/GeoInfo.Shahrestan.xlsx
InflationDataFilePath: ../Data/inflation.xlsx
InflationDataSheet: Data
MDS_CFN: CompressedFileNames
MDS_P1Cols: P1Cols
MDS_P2Cols: P2Cols
MDS_Geo2: Geo2
MDS_Geo4: Geo4
MDS_GeoX: GeoX
MDS_GeoX_New: GeoX_New
MDS_EC_A: EduCodes-A
MDS_EC_B: EduCodes-B
MDS_EC_C: EduCodes-C
MDS_EC_D: EduCodes-D
MDS_Food: FoodTables
MDS_FoodGroups: FoodGroupTables
MDS_FoodGroupsTotalNutrition: FoodGroupTablesTotalNutrition
MDS_InfantMilk: InfantMilkTables
MDS_Cigar: CigarTables
MDS_Cloth: ClothTables
MDS_HouseandEnergy: HouseandEnergyTables
MDS_Energy: EnergyTables
MDS_Furniture: FurnitureTables
MDS_Transportation: TransportationTables
MDS_Communication: CommunicationTables
MDS_Amusement: AmusementTables
MDS_Hotel: HotelTables
MDS_Restaurant: RestaurantTables
MDS_Other: OtherTables
MDS_Durable: DurableTables
MDS_DurableGroups: DurableGroups
MDS_DurableItems: DurableItems
MDS_DurableItemsDepr: DurableItemsDepr
MDS_Finance: FinanceTables
MDS_Investment: InvestmentTables
MDS_Medical: MedicalTables
MDS_Hygiene: HygieneTables
MDS_Loans: LoanTables
MDS_FinServices: FinServicesTables
MDS_House: HouseTables
MDS_Education: EducationTables
MDS_Insurance: InsuranceTables
MDS_ActivityState: ActivityStateTables
MDS_PubWage: PubWageTable
MDS_PrvWage: PrvWageTable
MDS_AgriInc: AgriIncTable
MDS_BussInc: BussIncTable
MDS_OtherInc: OthrIncTable
MDS_Retirement: RetirementTables
MDS_Interest: InterestTables
MDS_Rent: RentTables
MDS_Aid: AidTables
MDS_Homemade: HomemadeTables
MDS_Intra: IntraTables
MDS_Subsidy: SubsidyTable
MDS_Rough_Weights: RegionWeights
OutFoodKCXShare: 0.3
OutFoodKCXShare12: 0.4
OutFoodKCXShare3456: 0.2
OutFoodKCXShare78910: 0.1
KCaloryNeed_Adult: 2100.0
KCaloryNeed_Adult_WorldBank: 2100.0
KCaloryNeed_Adult_NutritionInstitute: 2400.0
KCaloryNeed_Child: 1800.0
KCaloryNeed_B1: 850.0
KCaloryNeed_G1: 780.0
KCaloryNeed_B2: 1250.0
KCaloryNeed_G2: 1190.0
KCaloryNeed_B3: 1430.0
KCaloryNeed_G3: 1330.0
KCaloryNeed_B4: 1560.0
KCaloryNeed_G4: 1440.0
KCaloryNeed_B5: 1690.0
KCaloryNeed_G5: 1540.0
KCaloryNeed_B6: 1980.0
KCaloryNeed_G6: 1730.0
KCaloryNeed_B7: 2370.0
KCaloryNeed_G7: 2040.0
KCaloryNeed_B8: 2700.0
KCaloryNeed_G8: 2120.0
KCaloryNeed_B9: 2460.0
KCaloryNeed_G9: 1990.0
KCaloryNeed_B10: 2010.0
KCaloryNeed_G10: 1780.0

ProteinNeed_B1: 12.6
ProteinNeed_G1: 11.7
ProteinNeed_B2: 13.9
ProteinNeed_G2: 13.1
ProteinNeed_B3: 13.9
ProteinNeed_G3: 13.5
ProteinNeed_B4: 15.7
ProteinNeed_G4: 15.3
ProteinNeed_B5: 26.2
ProteinNeed_G5: 26.5
ProteinNeed_B6: 49.3
ProteinNeed_G6: 60
ProteinNeed_B7: 65.5
ProteinNeed_G7: 58.2
ProteinNeed_B8: 66
ProteinNeed_G8: 59
ProteinNeed_B9: 66
ProteinNeed_G9: 59


KCaloryNeed_NutInst_B1: 705.0
KCaloryNeed_NutInst_G1: 643.0
KCaloryNeed_NutInst_B2: 948.0
KCaloryNeed_NutInst_G2: 865.0
KCaloryNeed_NutInst_B3: 1120.0
KCaloryNeed_NutInst_G3: 1047.0
KCaloryNeed_NutInst_B4: 1360.0
KCaloryNeed_NutInst_G4: 1242.0
KCaloryNeed_NutInst_B5: 1927.0
KCaloryNeed_NutInst_G5: 1782.0
KCaloryNeed_NutInst_B6: 3036.0
KCaloryNeed_NutInst_G6: 2434.0
KCaloryNeed_NutInst_B7: 3029.0
KCaloryNeed_NutInst_G7: 2300.0
KCaloryNeed_NutInst_B8: 2900.0
KCaloryNeed_NutInst_G8: 2200.0
KCaloryNeed_NutInst_B9: 2350.0
KCaloryNeed_NutInst_G9: 2000.0
KCaloryNeed_lactating: 500.0


KCaloryNeed_NutInst_L15: 1785
KCaloryNeed_NutInst_H15: 2415
KCaloryNeed_NutInst_L20: 1680
KCaloryNeed_NutInst_H20: 2520
KCaloryNeed_NutInst_L25: 1575
KCaloryNeed_NutInst_H25: 2625
KCaloryNeed_NutInst_L30: 1470
KCaloryNeed_NutInst_H30: 2730

ProteinNeed_NutInst_L15: 58.20
ProteinNeed_NutInst_H15: 78.74
ProteinNeed_NutInst_L20: 54.78
ProteinNeed_NutInst_H20: 82.17
ProteinNeed_NutInst_L25: 51.35
ProteinNeed_NutInst_H25: 85.59
ProteinNeed_NutInst_L30: 48
ProteinNeed_NutInst_H30: 89


VitaminANeed_NutInst_L15: 589.612
VitaminANeed_NutInst_H15: 797.71
VitaminANeed_NutInst_L20: 555
VitaminANeed_NutInst_H20: 832.4
VitaminANeed_NutInst_L25: 520.24
VitaminANeed_NutInst_H25: 867.07
VitaminANeed_NutInst_L30: 485.5
VitaminANeed_NutInst_H30: 901.7

RiboflavinNeed_NutInst_L15: 0.9018
RiboflavinNeed_NutInst_H15: 1.2201
RiboflavinNeed_NutInst_L20: 0.848
RiboflavinNeed_NutInst_H20: 1.273
RiboflavinNeed_NutInst_L25: 0.7957
RiboflavinNeed_NutInst_H25: 1.326
RiboflavinNeed_NutInst_L30: 0.742
RiboflavinNeed_NutInst_H30: 1.38


FeNeed_NutInst_L15: 10.891
FeNeed_NutInst_H15: 14.7359
FeNeed_NutInst_L20: 10.25
FeNeed_NutInst_H20: 15.37
FeNeed_NutInst_L25: 9.61
FeNeed_NutInst_H25: 16.01
FeNeed_NutInst_L30: 8.97
FeNeed_NutInst_H30: 16.658


CalciumNeed_NutInst_L15: 557.63
CalciumNeed_NutInst_H15: 754.44
CalciumNeed_NutInst_L20: 524.83
CalciumNeed_NutInst_H20: 787.24
CalciumNeed_NutInst_L25: 492
CalciumNeed_NutInst_H25: 820
CalciumNeed_NutInst_L30: 459.22
CalciumNeed_NutInst_H30: 852.84


ConsumptionCols:
- OriginalFoodExpenditure
- FoodOtherExpenditure
- Cigar_Exp
- Cloth_Exp
- Amusement_Exp
- Communication_Exp
- House_Exp
- Energy_Exp
- Furniture_Exp
- Hotel_Exp
- Restaurant_Exp
- Hygiene_Exp
- Transportation_Exp
- Other_Exp
- Add_to_NonDurable
- OwnedDurableItemsDepreciation
ExpenditureCols:
- OriginalFoodExpenditure
- FoodOtherExpenditure
- Cigar_Exp
- Cloth_Exp
- Amusement_Exp
- Communication_Exp
- House_Exp
- Energy_Exp
- Furniture_Exp
- Hotel_Exp
- Restaurant_Exp
- Hygiene_Exp
- Transportation_Exp
- Other_Exp
- Add_to_NonDurable
- Medical_Exp
- Durable_Dep
- Durable_NoDep
- Durable_Emergency
InitialPoorPercentileMax: 35.0
SectorsNumbers:
- 1
- 2
- 3
- 4
- 5
SectorsNames:
- Public
- Cooperative
- Private
- BussP
- Agri
D80LinkSource: ../Data/D80Link.accdb
D80LinkDest: C:/HEIS/DataAccess/D80Link.accdb

