library(yaml)
OS <- ifelse(version$os=="linux-gnu","Linux","Windows")
if(OS=="Linux"){
  HEISPath         = "/media/majid/Document/HEIS/"
}else{
 HEISPath           = "D:/HEIS/"
}
HEISCompressedPath = paste0(HEISPath,"DataCompressed/")
HEISAccessPath     = paste0(HEISPath,"DataAccess/")
HEISRawPath        = paste0(HEISPath,"DataRaw/")
HEISProcessedPath  = paste0(HEISPath,"DataProcessed/")
HEISResultsPath    = paste0(HEISPath,"DataResults/")
D80LinkDest        = paste0(HEISAccessPath,"D80Link.accdb")


Settings <- list(HEISPath          =HEISPath,
                 HEISCompressedPath=HEISCompressedPath,
                 HEISAccessPath    =HEISAccessPath,
                 HEISRawPath       =HEISRawPath,
                 HEISProcessedPath =HEISProcessedPath,
                 HEISResultsPath   =HEISResultsPath,
                 HEISWeightsPath   ="../Data/SamplingWeights/",
                 HEISWeightFileName="HHWeights",
                 startyear=63,
                 endyear=95,
                 OS=OS,
                 # RawDataWebAddress ="http://www.amar.org.ir/Portals/0/amarmozuii/hazinedaramad/",
                 RawDataWebAddress ="https://www.amar.org.ir/Portals/0/amarmozuii/re_DataRaw_63_95_Info/",
                 MetaDataFilePath  = "../Data/MetaData.xlsx",
                 MDS_CFN           = "CompressedFileNames",              # MetaData Sheet: Compressed File Names
                 MDS_P1Cols        = "P1Cols",                           # MetaData Sheet: Columns of P1 Table
                 MDS_EC_A          = "EduCodes-A",
                 MDS_EC_B          = "EduCodes-B",
                 MDS_EC_C          = "EduCodes-C",
                 MDS_Food          = "FoodTables",
                 MDS_Ghand         = "Ghand",
                 MDS_Hoboobat      = "Hoboobat",
                 MDS_Roghan        = "Roghan",
                 MDS_Berenj        ="Berenj",
                 MDS_Makarooni     = "Makarooni",
                 MDS_Sibzamini     = "Sibzamini",
                 MDS_Nan           ="Nan",
                 MDS_Goosht        ="Goosht",
                 MDS_Morgh         ="Morgh",
                 MDS_Mahi          = "Mahi",
                 MDS_Shir          = "Shir",
                 MDS_Mast          ="Mast",
                 MDS_Panir         = "Panir",
                 MDS_Tokhmemorgh    = "Tokhmemorgh",
                 MDS_Mive          = "Mive",
                 MDS_Sabzi         ="Sabzi",
                 MDS_Biscuit       = "Biscuit",
                 MDS_Khoshkbar     = "Khoshkbar",
                 MDS_Shirini       = "Shirini",
                 MDS_Cigar         = "CigarTables",
                 MDS_Cloth         = "ClothTables",
                 MDS_Energy        = "EnergyTables",
                 MDS_Furniture     = "FurnitureTables",
                 MDS_Transportation= "TransportationTables",
                 MDS_Communication = "CommunicationTables",
                 MDS_Amusement     = "AmusementTables",
                 MDS_Hotel         = "HotelTables",
                 MDS_Other         = "OtherTables",
                 MDS_Durable       = "DurableTables",
                 MDS_Investment    = "InvestmentTables",
                 MDS_Medical       = "MedicalTables",
                 MDS_Behdasht      = "BehdashtTables",
                 MDS_Loans         = "LoanTables",
                 MDS_House         = "HouseTables",
                 MDS_Education     = "EducationTables",
                 MDS_Insurance     = "InsuranceTables",
                 MDS_ActivityState = "ActivityStateTables",
                 MDS_PubWage       = "PubWageTable",
                 MDS_PrvWage       = "PrvWageTable",
                 MDS_AgriInc       = "AgriIncTable",
                 MDS_BussInc       = "BussIncTable",
                 MDS_OtherInc     = "OthrIncTable",
                 MDS_Retirement    = "RetirementTables",
                 MDS_Interest      = "InterestTables",
                 MDS_Rent          = "RentTables",
                 MDS_Aid           = "AidTables",
                 MDS_Homemade      = "HomemadeTables",
                 MDS_Intra         = "IntraTables",
                 MDS_SubsidyWage   = "SubsidyTable",
                 MDS_Rough_Weights = "RegionWeights",
                 SectorsNumbers    = 1:5,
                 SectorsNames      = c("Public","Cooperative","Private","BussP","Agri"),
                 weightsFile       ="../Data/AllWeights.rda",
                 D80LinkSource     ="../Data/D80Link.accdb",
                 D80LinkDest       =D80LinkDest
)
write(as.yaml(Settings),file = "Settings.yaml")