source("modifySettings.R")
#source("104-ExtractAccessFiles.R")
#source("105-ReadWriteIntoR.R")
source("111-HHBase.R")
source("112-InfantMilkExpenditures.R")
source("113-Demo.R")
source("121-HHHouseProperties.R")
source("131-HHFood Expenditures.R")
source("132-HHNonFood Expenditures.R")
source("133-HHDurableExpenditures.R")
source("141-Breaking Durable goods in four sections.R")
source("142-Calculate_OwnedDurableItemsDepreciation_FunctionDef.R")
source("143-CalculateDepreciation-FirstRound-BasedOnTotalSample.R")
source("151-Food Groups for Calorie.R")
source("152-Total Food Calories (17 groups).R")
source("153-Specification of food original groups.R")
source("161-Step1-MergeData.R")
source("162-Step2-CaloryEqSize.R")
source("163-Step3-Add_OutofHouseCalories.R")
source("164-Step4-IterativeRealDeciles.R")
source("165-Step5-AddClusterInfo.R")
source("166-Step6-FoodPoor.R")
source("167-Step7-Engel.R")
source("168-Step8-PovertyStats.R")
#source("170-Deciling for normal calculations.R")