HEISPath: D:/HEIS/
HEISCompressedPath: D:/HEIS/DataCompressed/
HEISAccessPath: D:/HEIS/DataAccess/
HEISRawPath: D:/HEIS/DataRaw/
HEISProcessedPath: D:/HEIS/DataProcessed/
HEISResultsPath: D:/HEIS/DataResults/
startyear: 63.0
endyear: 94.0
OS: windows
RawDataWebAddress: http://www.amar.org.ir/Portals/0/amarmozuii/hazinedaramad/
MetaDataFilePath: ../Data/MetaData.xlsx
MDS_CFN: CompressedFileNames
MDS_P1Cols: P1Cols
MDS_EC_A: EduCodes-A
MDS_EC_B: EduCodes-B
MDS_EC_C: EduCodes-C
MDS_Food: FoodTables
MDS_Medical: MedicalTables
MDS_Cloth: ClothTables
MDS_Energy: EnergyTables
MDS_Furniture: FurnitureTables
MDS_Transportation: TransportationTables
MDS_Communication: CommunicationTables
MDS_Amusement: AmusementTables
MDS_Loans: LoanTables
MDS_House: HouseTables
MDS_Education: EducationTables
MDS_Insurance: InsuranceTables
MDS_PubWage: PubWageTable
MDS_PrvWage: PrvWageTable
MDS_AgriWage: AggrIncTable
MDS_BussWage: BussIncTable
MDS_OtherWage: OthrIncTable
MDS_SubsidyWage: SubsidyTable
MDS_Rough_Weights: RegionWeights
weightsFile: ../Data/AllWeights.rda
D80LinkSource: ../Data/D80Link.accdb
D80LinkDest: D:/HEIS/DataAccess/D80Link.accdb

