HEISPath: C:/HEIS/
HEISCompressedPath: C:/HEIS/DataCompressed/
HEISAccessPath: C:/HEIS/DataAccess/
HEISRawPath: C:/HEIS/DataRaw/
HEISProcessedPath: C:/HEIS/DataProcessed/
HEISResultsPath: C:/HEIS/DataResults/
HEISWeightsPath: ../Data/SamplingWeights/
HEISWeightFileName: HHWeights
HEISCountyCodePath: ../Data/CountyCodes8791/
HEISCountyCodeFileName: ShCode
startyear: 90.0
endyear: 97.0
baseyear: 95.0
OS: Windows
RawDataWebAddress: https://www.amar.org.ir/Portals/0/amarmozuii/re_DataRaw_63_95_Info/
MetaDataFilePath: ../Data/MetaData.xlsx
GeoInfoFilePath: ../Data/GeoInfo.Shahrestan.xlsx
MDS_CFN: CompressedFileNames
MDS_P1Cols: P1Cols
MDS_P2Cols: P2Cols
MDS_EC_A: EduCodes-A
MDS_EC_B: EduCodes-B
MDS_EC_C: EduCodes-C
MDS_EC_D: EduCodes-D
MDS_Food: FoodTables
MDS_Sheep: SheepTables
MDS_Cow: CowTables
MDS_Shir: ShirTables
MDS_Mast: MastTables
MDS_Panir: PanirTables
MDS_Morgh: MorghTables
MDS_BerenjI: BerenjITables
MDS_BerenjF: BerenjFTables
MDS_Roghan: RoghanTables
MDS_Tokhmemorgh: TokhmemorghTables
MDS_Ghand: GhandTables
MDS_Shekar: ShekarTables
MDS_Nokhod: NokhodTables
MDS_Lapeh: LapehTables
MDS_Loobia_Chiti: Loobia_ChitiTables
MDS_Loobia_Ghermez: Loobia_GhermezTables
MDS_Adas: AdasTables
MDS_FoodGroups: FoodGroupTables
MDS_Cigar: CigarTables
MDS_Cloth: ClothTables
MDS_HouseandEnergy: HouseandEnergyTables
MDS_Energy: EnergyTables
MDS_Furniture: FurnitureTables
MDS_Transportation: TransportationTables
MDS_Benzin: BenzinTables
MDS_Bargh: BarghTables
MDS_Gaz: GazTables
MDS_NaftSefid: NaftSefidTables
MDS_Communication: CommunicationTables
MDS_Amusement: AmusementTables
MDS_HotelRestaurant: HotelRestaurantTables
MDS_Other: OtherTables
MDS_Durable: DurableTables
MDS_Investment: InvestmentTables
MDS_Medical: MedicalTables
MDS_Hygiene: HygieneTables
MDS_Loans: LoanTables
MDS_FinServices: FinServicesTables
MDS_House: HouseTables
MDS_Education: EducationTables
MDS_Insurance: InsuranceTables
MDS_ActivityState: ActivityStateTables
MDS_PubWage: PubWageTable
MDS_PrvWage: PrvWageTable
MDS_AgriInc: AgriIncTable
MDS_BussInc: BussIncTable
MDS_OtherInc: OthrIncTable
MDS_Retirement: RetirementTables
MDS_Interest: InterestTables
MDS_Rent: RentTables
MDS_Aid: AidTables
MDS_Homemade: HomemadeTables
MDS_Intra: IntraTables
MDS_SubsidyWage: SubsidyTable
MDS_Rough_Weights: RegionWeights
OutFoodKCXShare: 0.3
OutFoodKCXShare12: 0.4
OutFoodKCXShare3456: 0.2
OutFoodKCXShare78910: 0.1
KCaloryNeed_Adult: 2100.0
KCaloryNeed_Adult_WorldBank: 2100.0
KCaloryNeed_Adult_Anstitoo: 2400.0
KCaloryNeed_Child: 1800.0
KCaloryNeed_B1: 850.0
KCaloryNeed_G1: 780.0
KCaloryNeed_B2: 1250.0
KCaloryNeed_G2: 1190.0
KCaloryNeed_B3: 1430.0
KCaloryNeed_G3: 1330.0
KCaloryNeed_B4: 1560.0
KCaloryNeed_G4: 1440.0
KCaloryNeed_B5: 1690.0
KCaloryNeed_G5: 1540.0
KCaloryNeed_B6: 1980.0
KCaloryNeed_G6: 1730.0
KCaloryNeed_B7: 2370.0
KCaloryNeed_G7: 2040.0
KCaloryNeed_B8: 2700.0
KCaloryNeed_G8: 2120.0
KCaloryNeed_B9: 2460.0
KCaloryNeed_G9: 1990.0
KCaloryNeed_B10: 2010.0
KCaloryNeed_G10: 1780.0
KCaloryNeed_A_B1: 705.0
KCaloryNeed_A_G1: 643.0
KCaloryNeed_A_B2: 948.0
KCaloryNeed_A_G2: 865.0
KCaloryNeed_A_B3: 1120.0
KCaloryNeed_A_G3: 1047.0
KCaloryNeed_A_B4: 1360.0
KCaloryNeed_A_G4: 1242.0
KCaloryNeed_A_B5: 1927.0
KCaloryNeed_A_G5: 1782.0
KCaloryNeed_A_B6: 3036.0
KCaloryNeed_A_G6: 2434.0
KCaloryNeed_A_B7: 3029.0
KCaloryNeed_A_G7: 2300.0
KCaloryNeed_A_B8: 2900.0
KCaloryNeed_A_G8: 2200.0
KCaloryNeed_A_B9: 2350.0
KCaloryNeed_A_G9: 2000.0
KCaloryNeed_lactating: 500.0
InitialPoorPercentile:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
SectorsNumbers:
- 1
- 2
- 3
- 4
- 5
SectorsNames:
- Public
- Cooperative
- Private
- BussP
- Agri
D80LinkSource: ../Data/D80Link.accdb
D80LinkDest: C:/HEIS/DataAccess/D80Link.accdb

