HEISPath: C:/HEIS/
HEISCompressedPath: C:/HEIS/DataCompressed/
HEISAccessPath: C:/HEIS/DataAccess/
HEISRawPath: C:/HEIS/DataRaw/
HEISProcessedPath: C:/HEIS/DataProcessed/
HEISResultsPath: C:/HEIS/DataResults/
HEISWeightsPath: ../Data/SamplingWeights/
HEISWeightFileName: HHWeights
HEISCountyCodePath: ../Data/CountyCodes8791/
HEISCountyCodeFileName: ShCode
startyear: 77.0
endyear: 97.0
baseyear: 95.0
OS: Windows
RawDataWebAddress: https://www.amar.org.ir/Portals/0/amarmozuii/re_DataRaw_63_95_Info/
MetaDataFilePath: ../Data/MetaData.xlsx
GeoInfoFilePath: ../Data/GeoInfo.Shahrestan.xlsx
MDS_CFN: CompressedFileNames
MDS_P1Cols: P1Cols
MDS_P2Cols: P2Cols
MDS_EC_A: EduCodes-A
MDS_EC_B: EduCodes-B
MDS_EC_C: EduCodes-C
MDS_EC_D: EduCodes-D
MDS_Food: FoodTables
MDS_Sheep: SheepTables
MDS_Cow: CowTables
MDS_Shir: ShirTables
MDS_Mast: MastTables
MDS_Panir: PanirTables
MDS_Morgh: MorghTables
MDS_BerenjI: BerenjITables
MDS_BerenjF: BerenjFTables
MDS_Roghan: RoghanTables
MDS_Tokhmemorgh: TokhmemorghTables
MDS_Ghand: GhandTables
MDS_Shekar: ShekarTables
MDS_Nokhod: NokhodTables
MDS_Lapeh: LapehTables
MDS_Loobia_Chiti: Loobia_ChitiTables
MDS_Loobia_Ghermez: Loobia_GhermezTables
MDS_Adas: AdasTables
MDS_FoodGroups: FoodGroupTables
MDS_Cigar: CigarTables
MDS_Cloth: ClothTables
MDS_HouseandEnergy: HouseandEnergyTables
MDS_Energy: EnergyTables
MDS_Furniture: FurnitureTables
MDS_Transportation: TransportationTables
MDS_Benzin: BenzinTables
MDS_Bargh: BarghTables
MDS_Gaz: GazTables
MDS_NaftSefid: NaftSefidTables
MDS_Communication: CommunicationTables
MDS_Amusement: AmusementTables
MDS_HotelRestaurant: HotelRestaurantTables
MDS_Other: OtherTables
MDS_Durable: DurableTables
MDS_Investment: InvestmentTables
MDS_Medical: MedicalTables
MDS_Hygiene: HygieneTables
MDS_Loans: LoanTables
MDS_House: HouseTables
MDS_Education: EducationTables
MDS_Insurance: InsuranceTables
MDS_ActivityState: ActivityStateTables
MDS_PubWage: PubWageTable
MDS_PrvWage: PrvWageTable
MDS_AgriInc: AgriIncTable
MDS_BussInc: BussIncTable
MDS_OtherInc: OthrIncTable
MDS_Retirement: RetirementTables
MDS_Interest: InterestTables
MDS_Rent: RentTables
MDS_Aid: AidTables
MDS_Homemade: HomemadeTables
MDS_Intra: IntraTables
MDS_SubsidyWage: SubsidyTable
MDS_Rough_Weights: RegionWeights
OutFoodKCXShare: 0.3
OutFoodKCXShare12: 0.4
OutFoodKCXShare3456: 0.2
OutFoodKCXShare78910: 0.1
KCaloryNeed_Adult: 2100.0
KCaloryNeed_Adult_WorldBank: 2100.0
KCaloryNeed_Adult_Anstitoo: 2400.0
KCaloryNeed_Child: 1800.0
KCaloryNeed_B0: 850.0
KCaloryNeed_B1: 1250.0
KCaloryNeed_B2: 1356.0
KCaloryNeed_B3: 1582.0
KCaloryNeed_B4: 1728.0
KCaloryNeed_B5: 1838.0
KCaloryNeed_B6: 1922.0
KCaloryNeed_B7: 1980.0
KCaloryNeed_B8: 2058.0
KCaloryNeed_B9: 2136.0
KCaloryNeed_B10: 2214.0
KCaloryNeed_B11: 2292.0
KCaloryNeed_B12: 2370.0
KCaloryNeed_B13: 2436.0
KCaloryNeed_B14: 2502.0
KCaloryNeed_B15: 2568.0
KCaloryNeed_B16: 2634.0
KCaloryNeed_B17: 2700.0
KCaloryNeed_B18: 2652.0
KCaloryNeed_B19: 2604.0
KCaloryNeed_B20: 2556.0
KCaloryNeed_B21: 2508.0
KCaloryNeed_B22: 2460.0
KCaloryNeed_B23: 2460.0
KCaloryNeed_B24: 2460.0
KCaloryNeed_B25: 2460.0
KCaloryNeed_B26: 2460.0
KCaloryNeed_B27: 2460.0
KCaloryNeed_B28: 2460.0
KCaloryNeed_B29: 2460.0
KCaloryNeed_B30: 2460.0
KCaloryNeed_B31: 2460.0
KCaloryNeed_B32: 2460.0
KCaloryNeed_B33: 2460.0
KCaloryNeed_B34: 2460.0
KCaloryNeed_B35: 2460.0
KCaloryNeed_B36: 2460.0
KCaloryNeed_B37: 2460.0
KCaloryNeed_B38: 2460.0
KCaloryNeed_B39: 2460.0
KCaloryNeed_B40: 2460.0
KCaloryNeed_B41: 2460.0
KCaloryNeed_B42: 2460.0
KCaloryNeed_B43: 2460.0
KCaloryNeed_B44: 2460.0
KCaloryNeed_B45: 2460.0
KCaloryNeed_B46: 2460.0
KCaloryNeed_B47: 2460.0
KCaloryNeed_B48: 2460.0
KCaloryNeed_B49: 2460.0
KCaloryNeed_B50: 2460.0
KCaloryNeed_B51: 2460.0
KCaloryNeed_B52: 2460.0
KCaloryNeed_B53: 2460.0
KCaloryNeed_B54: 2460.0
KCaloryNeed_B55: 2460.0
KCaloryNeed_B56: 2460.0
KCaloryNeed_B57: 2460.0
KCaloryNeed_B58: 2370.0
KCaloryNeed_B59: 2280.0
KCaloryNeed_B60: 2190.0
KCaloryNeed_B61: 2100.0
KCaloryNeed_B62: 2010.0
KCaloryNeed_B63: 2010.0
KCaloryNeed_B64: 2010.0
KCaloryNeed_B65: 2010.0
KCaloryNeed_B66: 2010.0
KCaloryNeed_B67: 2010.0
KCaloryNeed_B68: 2010.0
KCaloryNeed_B69: 2010.0
KCaloryNeed_B70: 2010.0
KCaloryNeed_B71: 2010.0
KCaloryNeed_B72: 2010.0
KCaloryNeed_B73: 2010.0
KCaloryNeed_B74: 2010.0
KCaloryNeed_B75: 2010.0
KCaloryNeed_B76: 2010.0
KCaloryNeed_B77: 2010.0
KCaloryNeed_B78: 2010.0
KCaloryNeed_B79: 2010.0
KCaloryNeed_B80: 2010.0
KCaloryNeed_B81: 2010.0
KCaloryNeed_B82: 2010.0
KCaloryNeed_B83: 2010.0
KCaloryNeed_B84: 2010.0
KCaloryNeed_B85: 2010.0
KCaloryNeed_B86: 2010.0
KCaloryNeed_B87: 2010.0
KCaloryNeed_B88: 2010.0
KCaloryNeed_B89: 2010.0
KCaloryNeed_B90: 2010.0
KCaloryNeed_B91: 2010.0
KCaloryNeed_B92: 2010.0
KCaloryNeed_B93: 2010.0
KCaloryNeed_B94: 2010.0
KCaloryNeed_B95: 2010.0
KCaloryNeed_B96: 2010.0
KCaloryNeed_B97: 2010.0
KCaloryNeed_B98: 2010.0
KCaloryNeed_B99: 2010.0
KCaloryNeed_G0: 780.0
KCaloryNeed_G1: 1190.0
KCaloryNeed_G2: 1256.0
KCaloryNeed_G3: 1446.0
KCaloryNeed_G4: 1554.0
KCaloryNeed_G5: 1634.0
KCaloryNeed_G6: 1692.0
KCaloryNeed_G7: 1730.0
KCaloryNeed_G8: 1792.0
KCaloryNeed_G9: 1854.0
KCaloryNeed_G10: 1916.0
KCaloryNeed_G11: 1978.0
KCaloryNeed_G12: 2040.0
KCaloryNeed_G13: 2056.0
KCaloryNeed_G14: 2072.0
KCaloryNeed_G15: 2088.0
KCaloryNeed_G16: 2104.0
KCaloryNeed_G17: 2120.0
KCaloryNeed_G18: 2094.0
KCaloryNeed_G19: 2068.0
KCaloryNeed_G20: 2042.0
KCaloryNeed_G21: 2016.0
KCaloryNeed_G22: 1990.0
KCaloryNeed_G23: 1990.0
KCaloryNeed_G24: 1990.0
KCaloryNeed_G25: 1990.0
KCaloryNeed_G26: 1990.0
KCaloryNeed_G27: 1990.0
KCaloryNeed_G28: 1990.0
KCaloryNeed_G29: 1990.0
KCaloryNeed_G30: 1990.0
KCaloryNeed_G31: 1990.0
KCaloryNeed_G32: 1990.0
KCaloryNeed_G33: 1990.0
KCaloryNeed_G34: 1990.0
KCaloryNeed_G35: 1990.0
KCaloryNeed_G36: 1990.0
KCaloryNeed_G37: 1990.0
KCaloryNeed_G38: 1990.0
KCaloryNeed_G39: 1990.0
KCaloryNeed_G40: 1990.0
KCaloryNeed_G41: 1990.0
KCaloryNeed_G42: 1990.0
KCaloryNeed_G43: 1990.0
KCaloryNeed_G44: 1990.0
KCaloryNeed_G45: 1990.0
KCaloryNeed_G46: 1990.0
KCaloryNeed_G47: 1990.0
KCaloryNeed_G48: 1990.0
KCaloryNeed_G49: 1990.0
KCaloryNeed_G50: 1990.0
KCaloryNeed_G51: 1990.0
KCaloryNeed_G52: 1990.0
KCaloryNeed_G53: 1990.0
KCaloryNeed_G54: 1990.0
KCaloryNeed_G55: 1990.0
KCaloryNeed_G56: 1990.0
KCaloryNeed_G57: 1990.0
KCaloryNeed_G58: 1948.0
KCaloryNeed_G59: 1906.0
KCaloryNeed_G60: 1864.0
KCaloryNeed_G61: 1822.0
KCaloryNeed_G62: 1780.0
KCaloryNeed_G63: 1780.0
KCaloryNeed_G64: 1780.0
KCaloryNeed_G65: 1780.0
KCaloryNeed_G66: 1780.0
KCaloryNeed_G67: 1780.0
KCaloryNeed_G68: 1780.0
KCaloryNeed_G69: 1780.0
KCaloryNeed_G70: 1780.0
KCaloryNeed_G71: 1780.0
KCaloryNeed_G72: 1780.0
KCaloryNeed_G73: 1780.0
KCaloryNeed_G74: 1780.0
KCaloryNeed_G75: 1780.0
KCaloryNeed_G76: 1780.0
KCaloryNeed_G77: 1780.0
KCaloryNeed_G78: 1780.0
KCaloryNeed_G79: 1780.0
KCaloryNeed_G80: 1780.0
KCaloryNeed_G81: 1780.0
KCaloryNeed_G82: 1780.0
KCaloryNeed_G83: 1780.0
KCaloryNeed_G84: 1780.0
KCaloryNeed_G85: 1780.0
KCaloryNeed_G86: 1780.0
KCaloryNeed_G87: 1780.0
KCaloryNeed_G88: 1780.0
KCaloryNeed_G89: 1780.0
KCaloryNeed_G90: 1780.0
KCaloryNeed_G91: 1780.0
KCaloryNeed_G92: 1780.0
KCaloryNeed_G93: 1780.0
KCaloryNeed_G94: 1780.0
KCaloryNeed_G95: 1780.0
KCaloryNeed_G96: 1780.0
KCaloryNeed_G97: 1780.0
KCaloryNeed_G98: 1780.0
KCaloryNeed_G99: 1780.0
KCaloryNeed_A_B0: 705.0
KCaloryNeed_A_B1: 948.0
KCaloryNeed_A_B2: 1070.0
KCaloryNeed_A_B3: 1170.0
KCaloryNeed_A_B4: 1270.0
KCaloryNeed_A_B5: 1450.0
KCaloryNeed_A_B6: 1600.0
KCaloryNeed_A_B7: 1730.0
KCaloryNeed_A_B8: 1860.0
KCaloryNeed_A_B9: 1990.0
KCaloryNeed_A_B10: 2120.0
KCaloryNeed_A_B11: 2250.0
KCaloryNeed_A_B12: 2600.0
KCaloryNeed_A_B13: 2800.0
KCaloryNeed_A_B14: 3000.0
KCaloryNeed_A_B15: 3200.0
KCaloryNeed_A_B16: 3300.0
KCaloryNeed_A_B17: 3200.0
KCaloryNeed_A_B18: 3100.0
KCaloryNeed_A_B19: 3087.0
KCaloryNeed_A_B20: 3074.0
KCaloryNeed_A_B21: 3061.0
KCaloryNeed_A_B22: 3048.0
KCaloryNeed_A_B23: 3035.0
KCaloryNeed_A_B24: 3022.0
KCaloryNeed_A_B25: 3009.0
KCaloryNeed_A_B26: 2996.0
KCaloryNeed_A_B27: 2983.0
KCaloryNeed_A_B28: 2970.0
KCaloryNeed_A_B29: 2957.0
KCaloryNeed_A_B30: 2950.0
KCaloryNeed_A_B31: 2947.0
KCaloryNeed_A_B32: 2944.0
KCaloryNeed_A_B33: 2941.0
KCaloryNeed_A_B34: 2938.0
KCaloryNeed_A_B35: 2935.0
KCaloryNeed_A_B36: 2932.0
KCaloryNeed_A_B37: 2929.0
KCaloryNeed_A_B38: 2926.0
KCaloryNeed_A_B39: 2923.0
KCaloryNeed_A_B40: 2920.0
KCaloryNeed_A_B41: 2917.0
KCaloryNeed_A_B42: 2914.0
KCaloryNeed_A_B43: 2911.0
KCaloryNeed_A_B44: 2908.0
KCaloryNeed_A_B45: 2905.0
KCaloryNeed_A_B46: 2902.0
KCaloryNeed_A_B47: 2899.0
KCaloryNeed_A_B48: 2896.0
KCaloryNeed_A_B49: 2893.0
KCaloryNeed_A_B50: 2890.0
KCaloryNeed_A_B51: 2887.0
KCaloryNeed_A_B52: 2884.0
KCaloryNeed_A_B53: 2881.0
KCaloryNeed_A_B54: 2878.0
KCaloryNeed_A_B55: 2875.0
KCaloryNeed_A_B56: 2872.0
KCaloryNeed_A_B57: 2869.0
KCaloryNeed_A_B58: 2866.0
KCaloryNeed_A_B59: 2863.0
KCaloryNeed_A_B60: 2800.0
KCaloryNeed_A_B61: 2777.0
KCaloryNeed_A_B62: 2754.0
KCaloryNeed_A_B63: 2731.0
KCaloryNeed_A_B64: 2708.0
KCaloryNeed_A_B65: 2685.0
KCaloryNeed_A_B66: 2662.0
KCaloryNeed_A_B67: 2639.0
KCaloryNeed_A_B68: 2616.0
KCaloryNeed_A_B69: 2593.0
KCaloryNeed_A_B70: 2570.0
KCaloryNeed_A_B71: 2547.0
KCaloryNeed_A_B72: 2524.0
KCaloryNeed_A_B73: 2501.0
KCaloryNeed_A_B74: 2478.0
KCaloryNeed_A_B75: 2455.0
KCaloryNeed_A_B76: 2432.0
KCaloryNeed_A_B77: 2409.0
KCaloryNeed_A_B78: 2386.0
KCaloryNeed_A_B79: 2363.0
KCaloryNeed_A_B80: 2340.0
KCaloryNeed_A_B81: 2317.0
KCaloryNeed_A_B82: 2294.0
KCaloryNeed_A_B83: 2271.0
KCaloryNeed_A_B84: 2248.0
KCaloryNeed_A_B85: 2225.0
KCaloryNeed_A_B86: 2202.0
KCaloryNeed_A_B87: 2179.0
KCaloryNeed_A_B88: 2156.0
KCaloryNeed_A_B89: 2133.0
KCaloryNeed_A_B90: 2110.0
KCaloryNeed_A_B91: 2087.0
KCaloryNeed_A_B92: 2064.0
KCaloryNeed_A_B93: 2041.0
KCaloryNeed_A_B94: 2018.0
KCaloryNeed_A_B95: 1995.0
KCaloryNeed_A_B96: 1972.0
KCaloryNeed_A_B97: 1949.0
KCaloryNeed_A_B98: 1926.0
KCaloryNeed_A_B99: 1903.0
KCaloryNeed_A_G0: 675.0
KCaloryNeed_A_G1: 908.0
KCaloryNeed_A_G2: 1034.0
KCaloryNeed_A_G3: 1134.0
KCaloryNeed_A_G4: 1234.0
KCaloryNeed_A_G5: 1370.0
KCaloryNeed_A_G6: 1500.0
KCaloryNeed_A_G7: 1650.0
KCaloryNeed_A_G8: 1800.0
KCaloryNeed_A_G9: 1900.0
KCaloryNeed_A_G10: 2050.0
KCaloryNeed_A_G11: 2250.0
KCaloryNeed_A_G12: 2450.0
KCaloryNeed_A_G13: 2700.0
KCaloryNeed_A_G14: 2900.0
KCaloryNeed_A_G15: 2900.0
KCaloryNeed_A_G16: 2750.0
KCaloryNeed_A_G17: 2700.0
KCaloryNeed_A_G18: 2695.0
KCaloryNeed_A_G19: 2690.0
KCaloryNeed_A_G20: 2685.0
KCaloryNeed_A_G21: 2680.0
KCaloryNeed_A_G22: 2675.0
KCaloryNeed_A_G23: 2670.0
KCaloryNeed_A_G24: 2665.0
KCaloryNeed_A_G25: 2660.0
KCaloryNeed_A_G26: 2655.0
KCaloryNeed_A_G27: 2650.0
KCaloryNeed_A_G28: 2645.0
KCaloryNeed_A_G29: 2640.0
KCaloryNeed_A_G30: 2630.0
KCaloryNeed_A_G31: 2625.0
KCaloryNeed_A_G32: 2620.0
KCaloryNeed_A_G33: 2615.0
KCaloryNeed_A_G34: 2610.0
KCaloryNeed_A_G35: 2605.0
KCaloryNeed_A_G36: 2600.0
KCaloryNeed_A_G37: 2595.0
KCaloryNeed_A_G38: 2590.0
KCaloryNeed_A_G39: 2585.0
KCaloryNeed_A_G40: 2580.0
KCaloryNeed_A_G41: 2575.0
KCaloryNeed_A_G42: 2570.0
KCaloryNeed_A_G43: 2565.0
KCaloryNeed_A_G44: 2560.0
KCaloryNeed_A_G45: 2555.0
KCaloryNeed_A_G46: 2550.0
KCaloryNeed_A_G47: 2545.0
KCaloryNeed_A_G48: 2540.0
KCaloryNeed_A_G49: 2535.0
KCaloryNeed_A_G50: 2530.0
KCaloryNeed_A_G51: 2525.0
KCaloryNeed_A_G52: 2520.0
KCaloryNeed_A_G53: 2515.0
KCaloryNeed_A_G54: 2510.0
KCaloryNeed_A_G55: 2505.0
KCaloryNeed_A_G56: 2500.0
KCaloryNeed_A_G57: 2495.0
KCaloryNeed_A_G58: 2490.0
KCaloryNeed_A_G59: 2485.0
KCaloryNeed_A_G60: 2400.0
KCaloryNeed_A_G61: 2389.0
KCaloryNeed_A_G62: 2378.0
KCaloryNeed_A_G63: 2367.0
KCaloryNeed_A_G64: 2356.0
KCaloryNeed_A_G65: 2345.0
KCaloryNeed_A_G66: 2334.0
KCaloryNeed_A_G67: 2323.0
KCaloryNeed_A_G68: 2312.0
KCaloryNeed_A_G69: 2301.0
KCaloryNeed_A_G70: 2290.0
KCaloryNeed_A_G71: 2279.0
KCaloryNeed_A_G72: 2268.0
KCaloryNeed_A_G73: 2257.0
KCaloryNeed_A_G74: 2246.0
KCaloryNeed_A_G75: 2235.0
KCaloryNeed_A_G76: 2224.0
KCaloryNeed_A_G77: 2213.0
KCaloryNeed_A_G78: 2202.0
KCaloryNeed_A_G79: 2191.0
KCaloryNeed_A_G80: 2180.0
KCaloryNeed_A_G81: 2169.0
KCaloryNeed_A_G82: 2158.0
KCaloryNeed_A_G83: 2147.0
KCaloryNeed_A_G84: 2136.0
KCaloryNeed_A_G85: 2125.0
KCaloryNeed_A_G86: 2114.0
KCaloryNeed_A_G87: 2103.0
KCaloryNeed_A_G88: 2092.0
KCaloryNeed_A_G89: 2081.0
KCaloryNeed_A_G90: 2070.0
KCaloryNeed_A_G91: 2059.0
KCaloryNeed_A_G92: 2048.0
KCaloryNeed_A_G93: 2037.0
KCaloryNeed_A_G94: 2026.0
KCaloryNeed_A_G95: 2015.0
KCaloryNeed_A_G96: 2004.0
KCaloryNeed_A_G97: 1993.0
KCaloryNeed_A_G98: 1982.0
KCaloryNeed_A_G99: 1971.0
KCaloryNeed_lactating: 500.0
InitialPoorPercentile:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
SectorsNumbers:
- 1
- 2
- 3
- 4
- 5
SectorsNames:
- Public
- Cooperative
- Private
- BussP
- Agri
D80LinkSource: ../Data/D80Link.accdb
D80LinkDest: C:/HEIS/DataAccess/D80Link.accdb

