HEISPath: D:/HEIS/
HEISCompressedPath: D:/HEIS/DataCompressed/
HEISAccessPath: D:/HEIS/DataAccess/
HEISRawPath: D:/HEIS/DataRaw/
HEISProcessedPath: D:/HEIS/DataProcessed/
HEISResultsPath: D:/HEIS/DataResults/
HEISWeightsPath: ../Data/SamplingWeights/
HEISWeightFileName: HHWeights
startyear: 77.0
endyear: 96.0
baseyear: 95.0
OS: Windows
RawDataWebAddress: https://www.amar.org.ir/Portals/0/amarmozuii/re_DataRaw_63_96_Info/
MetaDataFilePath: ../Data/MetaData.xlsx
GeoInfoFilePath: ../Data/GeoInfo.Shahrestan.xlsx
MDS_CFN: CompressedFileNames
MDS_P1Cols: P1Cols
MDS_EC_A: EduCodes-A
MDS_EC_B: EduCodes-B
MDS_EC_C: EduCodes-C
MDS_Food: FoodTables
MDS_Sheep: SheepTables
MDS_Cow: CowTables
MDS_Morgh: MorghTables
MDS_FoodGroups: FoodGroupTables
MDS_Cigar: CigarTables
MDS_Cloth: ClothTables
MDS_Energy: EnergyTables
MDS_Furniture: FurnitureTables
MDS_Transportation: TransportationTables
MDS_Communication: CommunicationTables
MDS_Amusement: AmusementTables
MDS_Hotel: HotelTables
MDS_Other: OtherTables
MDS_Durable: DurableTables
MDS_Investment: InvestmentTables
MDS_Medical: MedicalTables
MDS_Behdasht: BehdashtTables
MDS_Loans: LoanTables
MDS_House: HouseTables
MDS_Education: EducationTables
MDS_Insurance: InsuranceTables
MDS_ActivityState: ActivityStateTables
MDS_PubWage: PubWageTable
MDS_PrvWage: PrvWageTable
MDS_AgriInc: AgriIncTable
MDS_BussInc: BussIncTable
MDS_OtherInc: OthrIncTable
MDS_Retirement: RetirementTables
MDS_Interest: InterestTables
MDS_Rent: RentTables
MDS_Aid: AidTables
MDS_Homemade: HomemadeTables
MDS_Intra: IntraTables
MDS_SubsidyWage: SubsidyTable
MDS_Rough_Weights: RegionWeights
OutFoodKCXShare: 0.3
OutFoodKCXShare12: 0.4
OutFoodKCXShare3456: 0.2
OutFoodKCXShare78910: 0.1
KCaloryNeed_Adult: 2100.0
KCaloryNeed_Child: 1800.0
InitialPoorPercentile:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
SectorsNumbers:
- 1
- 2
- 3
- 4
- 5
SectorsNames:
- Public
- Cooperative
- Private
- BussP
- Agri
D80LinkSource: ../Data/D80Link.accdb
D80LinkDest: D:/HEIS/DataAccess/D80Link.accdb

